apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRoleBinding
metadata:
  creationTimestamp: null
  name: eew-crb
roleRef:
  apiGroup: rbac.authorization.k8s.io
  kind: ClusterRole
  name: eew-cr
subjects:
- kind: ServiceAccount
  name: eew-sa
  namespace: {{ .Release.Namespace }}
