apiVersion: apps/v1
kind: Deployment
metadata:
  name: cpe
  labels:
    {{- include "cpe-chart.labels" . | nindent 4 }}
spec:
  {{- if not .Values.autoscaling.enabled }}
  replicas: {{ .Values.replicaCount }}
  {{- end }}
  selector:
    matchLabels:
      {{- include "cpe-chart.selectorLabels" . | nindent 6 }}
  template:
    metadata:
      {{- with .Values.podAnnotations }}
      annotations:
        {{- toYaml . | nindent 8 }}
      {{- end }}
      labels:
        {{- include "cpe-chart.selectorLabels" . | nindent 8 }}
    spec:
      containers:
        - name: cpe
          securityContext:
            {{- toYaml .Values.securityContext | nindent 12 }}
          image: {{ .Values.image.repository }}
          imagePullPolicy: {{ .Values.image.pullPolicy }}
          #uncomment below line to override the options, interval: frequency in seconds and supported list options are event,pod,node,namespace,service,pvc
          #args: ["-interval","30","-list","event,pod,node"]
